---
title: "Vector space"
description: "Vector spaces, subspaces, and subspace sums including direct sums — an augmented summary of Axler's LADR §1.B–1.C."
date: "2026-06-03"
date-modified: "2026-06-17"
categories: ["mathematics", "linear-algebra", "ladr"]
execute:
    echo: true
---

{{< include ../../_macros.qmd >}}

This is an augmented summary of Sections 1.B and 1.C of [Linear Algebra Done Right](https://linear.axler.net/index.html) by Sheldon Axler.

## Vector space
Suppose a set $V$ has **vector addition** $+:V\times V\to V$ defined on its elements, along with **scalar multiplication** $\cdot:\mb{F}\times V\to V$ defined with another set $\mb{F}$. For $V$ to be a **vector space**, it must form an Abelian group with respect to vector addition, while the following three requirements hold with respect to scalar multiplication:

- It is associative with $\mb{F}$'s internal multiplication: $(a_1a_2)v=a_1(a_2v)$.
- The multiplicative identity of $\mb{F}$, denoted $1$, is also an identity for scalar multiplication: $1v=v$.
- The distributive property holds, i.e. $a(v_1+v_2)=av_1+av_2$ and $(a_1+a_2)v=a_1v+a_2v$. 

Addition and multiplication are defined for $\mb{F}$ because it must be a **field**. $\mathbb{R}$ and $\mathbb{C}$ are concrete examples of fields.

<details class="example">
<summary>Trivial vector space</summary>

The empty set $\emptyset$ over some field is not a vector space, because it has no additive identity. The smallest vector space is the **trivial vector space** $\{0\}$.

</details>

<details class="example">
<summary>$\mb{F}^n$</summary>

For a given field $\mb{F}$, $\mb{F}^n$ denotes the set of all length-$n$ sequences of elements of $\mb{F}$. If we define vector addition and scalar multiplication as

$$
\begin{gather}
(x_1,\cdots,x_n)+(y_1,\cdots,y_n)=(x_1+y_1,\cdots,x_n+y_n)\\
\lambda(x_1,\cdots,x_n)=(\lambda x_1,\cdots,\lambda x_n),
\end{gather}
$$

we can directly check that $\mb{F}^n$ is a vector space over $\mb{F}$.

Furthermore, the set $\mb{F}^\infty$ of *infinite* sequences is also a vector space over $\mb{F}$.

</details>

<details class="example">
<summary>The function space $\mb{F}^S$</summary>

Let $\mb{F}^S$ be the set of all functions from a set $S$ to $\mb{F}$. Define the sum of two functions as the function that evaluates at each $x\in S$ as

$$(f+g)(x)=f(x)+g(x).$$

Define the product of a function with a scalar in $\mb{F}$ as the function that evaluates at each $x\in S$ as

$$(\lambda f)(x)=\lambda f(x).$$

We can check that $\mb{F}^S$ forms a vector space over $\mb{F}$. 

In particular, $\mb{F}^n$ and $\mb{F}^\infty$ are instances of $\mb{F}^S$ with $S=\{1,\cdots,n\}$ and $S=\mathbb{N}$ respectively. Each sequence $(x_1,x_2,\cdots)$ corresponds to a function that maps each index $i=1,2,\cdots$ to $x_i$: 

$$(x_1,x_2,\cdots)\leftrightarrow f(i)=x_i.$$

Under this correspondence, the element-wise addition and multiplication correspond to the function sum and product defined above:

$$
\begin{gather}
(x_1+y_1,x_2+y_2,\cdots)\leftrightarrow (f+g)(i)=f(i)+g(i)=x_i+y_i\\
(\lambda x_1,\lambda x_2,\cdots)\leftrightarrow (\lambda f)(i)=\lambda f(i)=\lambda x_i.
\end{gather}
$$

</details>

A **real vector space** is a vector space over $\mb{R}$. A **complex vector space** is a vector space over $\mb{C}$. Somewhat confusingly, we can speak of the real vector space $\mathbb{C}^n$, where we restrict the scalar multiplication to real numbers.

#### Basic properties
###### Uniqueness of identity and inverse
:::{#thm-}
As a group operation, the vector addition has a unique identity and inverse. 
:::

We write the unique identity as $0$^[This is the same symbol as the unique identity of $\mb{F}$, but there is no ambiguity because we always write the scalar before the vector.], and the unique inverse of $v$ as $-v$.

:::{#thm-}
The uniqueness of the inverse implies that $-(-v)=v$, because $v$ is the only vector that adds with $-v$ to produce $0$.
:::

###### Obtaining zero from scalar multiplication
:::{#thm-}
For any $v\in V$ and $a\in\mb{F}$, we have $0v=0$ and $a0=0$. 
:::

:::{.informal}
The zero vector is sufficient to kill the scalar multiple regardless of what the scalar is. The zero scalar is also sufficient to kill the scalar multiple regardless of the vector.
:::

<details class="proof">
<summary>Full proof</summary>

We have

$$0v=(0+0)v=0v+0v,$$

and subtracting $0v$ from both sides leads to $0v=0$. 

$a0=0$ is obtained in a similar manner.

</details>

:::{#thm-scalar-zero}
In fact, $a=0$ or $v=0$ are the only cases where you can obtain the zero vector by scalar multiplication.
:::

:::{.informal}
It is impossible to obtain a zero vector by multiplying a non-zero vector and a non-zero scalar together.
:::

:::{.proof-idea}
If $a\neq0$, then we can divide by $a$.
:::

<details class="proof">
<summary>Full proof</summary>

Suppose that $av=0$. If $a\neq0$, dividing by $a$ leads to $v=0$. So either $a=0$ or $v=0$.

</details>

###### Inverse as scalar multiplication
:::{#thm-neg-one}
Another "obvious" property that we can prove is $(-1)v=-v$.
:::

:::{.informal}
This equation looks familiar, but the underlying statement is quite convoluted: "scalar multiplication by the additive inverse of the multiplicative identity of $\mb{F}$ leads to the additive inverse of $v$". 
:::

<details class="proof">
<summary>Full proof</summary>

Since we have

$$
0=0v=(1+(-1))v=1v+(-1)v=v+(-1)v,
$$

we see that $(-1)v$ is the (unique) additive inverse of $v$.

</details>

## Subspace
Let's now think about subsets of $V$ that are vector spaces in their own right. These are called the **subspaces** of $V$. (Unfortunately, the motivations for defining this concept will not be forthcoming yet.) 

If someone brings us a subset $U\subseteq V$, we need not check through every vector space axiom to verify that $U$ is a subspace of $V$. 

:::{#thm-}
Since we inherit addition and scalar multiplication from $V$, we only have to verify that 

1. $U$ is closed under the inherited addition and scalar multiplication^[Previously, closure was not mentioned for vector addition, because we assumed that these binary operations map to the same set by definition.].
2. $0\in U$. 

Once these two properties hold, the vector space axioms are satisfied for $U$.
:::

<details class="example">
<summary>Subspaces of $\mathbb{R}^3$</summary>

The subspaces of $\mathbb{R}^3$ include lines and planes through the origin. In fact, along with $\{0\}$ and $\mathbb{R}^3$, these comprise the *only* subspaces of $\mathbb{R}^3$. This is an interesting result, but we cannot prove it just yet.

As an illustration, consider the subset

$$\{(x_1,x_2,x_3):x_1x_2x_3=0\}\subset\mathbb{R}^3.$$

This is not closed under addition because both $(1,1,0)$ and $(0,0,1)$ are in the set, but $(1,1,1)$ is not. (It is closed under scalar multiplication though.)

</details>

<details class="example">
<summary>Subspace formed by linear constraint</summary>

Consider the subset of $\mb{F}^3$ defined as

$$\{(x_1,x_2,x_3):ax_1+bx_2+cx_3=d\}$$

for some $a,b,c,d\in\mb{F}$. If $d=0$, then we can check that it is a subspace of $\mb{F}^3$. If $d\neq0$, then it is not a subspace because it does not contain $(0,0,0)$. (Actually, it is also not closed under vector addition or scalar multiplication.)

</details>

<details class="example">
<summary>$\mathbb{R}^2$ as subspace of $\mathbb{C}^2$</summary>

In a *complex* vector space $\mathbb{C}^2$, $\mathbb{R}^2$ is not a subspace because it is not closed under scalar multiplication by a non-real complex number.

In a *real* vector space $\mathbb{C}^2$, $\mathbb{R}^2$ is a subspace.

</details>

<details class="example">
<summary>Almost-subspaces of $\mathbb{R}^2$</summary>

The subset $\mathbb{Z}^2$ of $\mathbb{R}^2$ is closed under addition and the taking of additive inverses, but it is not closed under scalar multiplication.

The subset $\{(x,0)\}\cup\{(0,y)\}$ of $\mathbb{R}^2$ is closed under scalar multiplication but is not closed under addition.

</details>

#### Intersection and union of subspaces
###### Intersection
::: {#thm-subspace-intersection}
Suppose that $U_1$ and $U_2$ are subspaces of $V$. Then their intersection is also a subspace of $V$.
:::

:::{.informal}
An intersection of two subspaces is always another subspace.

This is trivial to prove, but the result is quite surprising if we think about it. It means that we can find a smaller closed subset within a closed subset, by intersecting with a different closed subset. 
:::

:::{.proof-idea}
Vectors in $U_1\cap U_2$ are closed within $U_1$ and $U_2$ separately. 
:::

<details class="proof">
<summary>Full proof</summary>

Let $u,u'\in U_1\cap U_2$. By the closures of $U_1$ and $U_2$, we have $u+u'\in U_1$ and $u+u'\in U_2$ respectively. Therefore, we have $u+u'\in U_1\cap U_2$, and so $U_1\cap U_2$ is closed under addition. 

Analogous reasoning shows that it is closed under scalar multiplication as well. 

Finally, both $U_1$ and $U_2$ contain $0$ because they are subspaces. Therefore, $U_1\cap U_2$ satisfies the conditions to be a subspace.

</details>

Furthermore, we can see that the same argument generalises to intersections of any finite number of subspaces. It also works for intersections of a countably infinite number of subspaces.

###### Union
What about the union of subspaces $U_1$ and $U_2$? In the trivial case where $U_1\subseteq U_2$, we have $U_1\cup U_2=U_2$, so we do obtain a subspace.

::: {#thm-subspace-union}
However, $U_1\cup U_2$ is not a subspace when one subspace does not contain the other.
:::

:::{.informal}
A union of two subspaces is never a subspace except in the trivial case.

This is also surprising. It means that we cannot combine two closed subsets to create a larger closed subset, no matter what these subsets are. 
:::

:::{.proof-idea}
The sum of two vectors lying in the symmetric difference escapes the union.
:::

<details class="proof">
<summary>Full proof</summary>

If one subspace does not contain the other, then there exist

$$
u_1\in U_1\cap U_2^c\quad\text{ and }\quad u_2\in U_2\cap U_1^c.
$$

If $u_1+u_2=u'_2$ for some $u'_2\in U_2$, then $u_1\in U_2$ by the closure of $U_2$, which is a contradiction. So we have $u_1+u_2\notin U_1$, and an analogous reasoning shows that $u_1+u_2\notin U_2$. 

Therefore, we find that $u_1+u_2\notin U_1\cup U_2$, and so $U_1\cup U_2$ is not closed under addition.

</details>

## Subspace sum
Suppose that $U_1,\cdots,U_n$ are subspaces of a vector space. We define their **sum** as the set

$$U_1+\cdots+U_n=\{u_1+\cdots+u_n:u_i\in U_i\}.$$

(This is yet another unmotivated definition.) 

:::{#thm-}
A sum of subspaces is itself a subspace.
:::

<details class="example">
<summary>Sum of $x$- and $y$-axes</summary>

If $U$ and $W$ are the "$x$- and $y$-axes" respectively, then $U+W$ is the "$x$-$y$ plane". That is, if $U$ and $W$ are subspaces of $\mb{F}^3$ where

$$U=\{(x,0,0):x\in\mb{F}\}\quad\text{and}\quad W=\{(0,y,0):y\in\mb{F}\},$$

then we see that their sum is given by

$$U+W=\{(x,y,0):x,y\in\mb{F}\}.$$

</details>

<details class="example">
<summary>Sum of two subspaces in $\mb{F}^4$</summary>

Let $U$ and $W$ be two subspaces of $\mb{F}^4$ defined by

$$
U=\{(x,x,y,y)\in\mb{F}^4:x,y\in\mb{F}\}\quad\text{and}\quad V=\{(x,x,x,y)\in\mb{F}^4:x,y\in\mb{F}\}.
$$

Then each vector in $U+V$ is produced from

$$(x,x,y,y)+(x',x',x',y')=(x+x',x+x',y+x',y+y'),$$

where each $x,y,x',y'\in\mb{F}$ can vary independently. We see that the second, third, and fourth components can vary independently, while the first component is equal to the second. This means that

$$U+V=\{(x,x,y,z)\in\mb{F}^4:x,y,z\in\mb{F}\}.$$

</details>

#### "Size" of subspace sum
:::{#thm-sum-smallest}
The sum of $U_1,\cdots,U_n$ is the *smallest* subspace^[This terminology is misleading, because this is not a matter of cardinality, but rather that of inclusion.] that contains the $U_i$s, in the sense that 

$$U_1+\cdots+U_n\subseteq W$$ 

for any other subspace $W$ containing them. 
:::

<details class="proof">
<summary>Full proof</summary>

This is almost definitional: any subspace containing the $U_i$s must be closed under the addition of their elements, and so must *at least* contain the elements of $U_1+\cdots+U_n$.

</details>

#### Subspace sum as binary operation
Here are some properties of the subspace sum, viewed as a binary operation on the subspaces of $V$.

###### Idempotence
:::{#thm-sum-idempotent}
The subspace sum is idempotent.
:::

<details class="proof">
<summary>Full proof</summary>

Consider

$$U+U=\{u+u':u,u'\in U\}.$$

By the closure of $U$, we have $U+U\subseteq U$. Meanwhile, $U\subseteq U+U$ because $0+u\in U+U$ for all $u\in U$. Therefore, we have $U+U=U$.

</details>

###### Commutativity
:::{#thm-sum-commutative}
The subspace sum is commutative.
:::

<details class="proof">
<summary>Full proof</summary>

Since vector addition is commutative, the set of all sums $u+v$ is equal to the set of all sums $v+u$.

</details>

###### Associativity
:::{#thm-sum-associative}
The subspace sum is associative.
:::

<details class="proof">
<summary>Full proof</summary>

Both $(U_1+U_2)+U_3$ and $U_1+(U_2+U_3)$ correspond to the same set of all sums $u_1+u_2+u_3$, because vector addition is associative.

</details>

###### Additive identity
$\{0\}$ is a subspace of any vector space, and it is the identity for the subspace sum because

$$
U+\{0\}=\{u+0:u\in U\}=U.
$$

###### Additive inverse
Since $U\subseteq U+W$, we can obtain $\{0\}$ from the vector addition only as $\{0\}+\{0\}$. In other words, only $\{0\}$ has an additive inverse, namely itself.

###### Cancellation property
:::{#thm-sum-cancellation}
The cancellation property does not hold for the subspace sum. 
:::

:::{.informal}
We cannot move from $U_1+W=U_2+W$ to $U_1=U_2$, however tempting it is (especially considering that the converse is trivially true).
:::

:::{.proof-idea}
We can find a counter-example in $\mathbb{R}^2$.
:::

<details class="proof">
<summary>Full proof</summary>

Consider $V=\mathbb{R}^2$ and let $U$ be the horizontal line through the origin. Then for any non-horizontal pair of lines $U_1$ and $U_2$ that go through the origin, we have $U_1+U=U_2+U$.

</details>

#### Direct sum
The vectors of a subspace sum may not uniquely decompose into the constituent subspaces, i.e. there may be multiple elements of $U_1\times\cdots\times U_n$ that lead to the same sum. 

<details class="example">
<summary>A non-unique decomposition</summary>

Consider the subspaces of $\mathbb{R}^3$ given by

$$
\begin{aligned}
U_1&=\{(a,b,0):a,b\in\mathbb{R}\}\\
U_2&=\{(0,c,d):c,d\in\mathbb{R}\}.
\end{aligned}
$$

Then we have $U_1+U_2=\mathbb{R}^3$, but every vector in $\mathbb{R}^3$ can be reached in infinitely different ways by adjusting the second entries of the summands. 

</details>

If every element *is* uniquely decomposable, then we say that the sum is a **direct sum**, and write $\oplus$ instead $+$. In other words, for every $w\in U_1+\cdots+U_n$, there is exactly one $(u_1,\cdots,u_n)\in U_1\times\cdots\times U_n$ that satisfies $w=u_1+\cdots+u_n$.

<details class="example">
<summary>A direct sum in $\mb{F}^4$</summary>

If $U$ and $W$ are subspaces of $\mb{F}^4$ with

$$U=\{(w,x,0,0):w,x\in\mb{F}\}\quad\text{and}\quad W=\{(0,0,y,z):y,z\in\mb{F}\},$$

then we see that $\mb{F}^4=U\oplus W$ because every vector $(w,x,y,z)\in\mb{F}^4$ can be uniquely decomposed as

$$u+v=(w,x,0,0)+(0,0,y,z).$$

</details>

<details class="example">
<summary>A non-direct sum in $\mb{F}^3$</summary>

The subspaces

$$
U_1=\{(x,y,0)\},\quad U_2=\{(0,0,z)\}\quad\text{and}\quad U_3=\{(0,y,y)\}
$$

do not form a direct sum, which can be verified by decomposing $0$ in two different ways:

$$(0,0,0)=(0,1,0)+(0,0,1)+(0,-1,-1)=(0,0,0)+(0,0,0)+(0,0,0).$$

</details>

###### Direct sum check
:::{#thm-direct-zero-check}
A subspace sum is direct if the zero vector is uniquely decomposable.
:::

:::{.informal}
From the definition alone, the directness of a sum seems impossible to check, because the unique decomposition property needs to hold for *every* vector of the vector space. But it turns out that we only need to check this for a single vector, which is a great relief.

Of course, the uniqueness of the decomposition of $0$ must be supplied elsewhere.
:::

:::{.proof-idea}
Consider $v_1-v_2$ when $v_1$ and $v_2$ are the two decompositions of the same vector.
:::

<details class="proof">
<summary>Full proof</summary>

Suppose that $0$ is uniquely decomposable as a sum $u_1+\cdots+u_n$. We know what this unique decomposition looks like, namely 

$$0=0+\cdots+0\in U_1+\cdots+U_n.$$ 

For an arbitrary $u\in U_1+\cdots+U_n$, suppose that it is decomposable in two ways as

$$u=u_1+\cdots+u_n=u'_1+\cdots+u'_n,$$

where $u_i,u'_i\in U_i$. This implies that

$$(u_1-u'_1)+\cdots+(u_n-u'_n)=0,$$

where $u_i-u'_i\in U_i$. By the unique decomposition of $0$, this implies that $u_i=u'_i$ for each $i$. So two decompositions of the same vector must always be equal.

</details>

###### Direct sum check for two subspaces
:::{#thm-trivial-intersection-implies-direct}
The sum of two subspaces is direct if their intersection contains only $0$.
:::

:::{.informal}
If we are dealing with a sum of two subspaces, then we can determine that their sum is direct simply by looking at their intersection.
:::

:::{.proof-idea}
$u+w=0$ implies that both $u$ and $w$ are in $U\cap W$.
:::

<details class="proof">
<summary>Full proof</summary>

Suppose that $U$ and $W$ are subspaces with $U\cap W=\{0\}$, and let $u+w$ be a decomposition of $0$ into $u\in U$ and $w\in W$.

Then we have the following implication:

$$u+w=0\implies u=-w\implies u,w\in U\cap W\implies u=w=0.$$

By the previous result, $U+W$ is a direct sum.

</details>

<details class="example">
<summary>Finding direct sum partner in $\mb{F}^5$</summary>

Consider a subspace of $\mb{F}^5$ defined as $U=\{(x,y,x+y,x-y,2x)\}$. Suppose we wish to find a subspace $W$ such that $\mb{F}^5=U\oplus W$.

Because only the first two components of $u\in U$ can vary independently, we have $\mb{F}^5=U+W$ if we define $W=\{(0,0,x,y,z)\}$. 

For $u\in U$ to have $0$ in the first two components, the other components also have to be zero. Therefore, $U\cap W=\{0\}$ and the sum is direct. 

</details>

<details class="example">
<summary>Even and odd functions</summary>

Consider $\mathbb{R}^\mathbb{R}$, the set of all real-valued functions on $\mathbb{R}$. Let $U_e$ and $U_o$ be the sets of even and odd functions respectively, which are subspaces of $\mathbb{R}^\mathbb{R}$. Since every $f:\mathbb{R}\to\mathbb{R}$ can be written as a sum of even and odd parts as

$$f(x)=\frac{1}{2}(f(x)+f(-x))+\frac{1}{2}(f(x)-f(-x)),$$

we have $\mathbb{R}^\mathbb{R}=U_e+U_o$. The sum is direct because the only function that is both even and odd is the zero function.

</details>

:::{#thm-direct-implies-trivial-intersection}
The converse direction also holds: $U\cap W=\{0\}$ whenever $U+W$ is a direct sum. 
:::

:::{.proof-idea}
$v+(-v)=0$ is a decomposition of $0$.
:::

<details class="proof">
<summary>Full proof</summary>

Suppose that $U+W$ is a direct sum, and let $v$ be an arbitrary vector in $U\cap W$. Since $U\cap W$ is a subspace, we have $-v\in U\cap W$. 

As such, $v+(-v)$ is a decomposition of $0$ into $v\in U$ and $-v\in W$. Since $U+W$ is direct, this implies that $v=-v=0$.

</details>

###### Cancellation property
:::{#thm-direct-cancellation}
The cancellation property still fails to hold when the sum is direct.
:::

:::{.informal}
We cannot move from $U_1\oplus W=U_2\oplus W$ to $U_1=U_2$, despite the unique decomposition in a direct sum (which may raise our hopes of cancellation).
:::

<details class="proof">
<summary>Full proof</summary>

In our counterexample against the cancellation property of the subspace sum, we see that $U_1+U$ and $U_2+U$ are both direct sums as the lines only intersect at the origin.

</details>