project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "posts/**/*.qmd"
    - "posts/**/*.md"
    - "!posts/_drafts/**"
    - "!content/**"

website:
  title: "J Lee's Blog"
  site-url: "https://r-lta.github.io"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    include-in-header:
      - text: |
          <script>
            window.MathJax = {
              tex: {
                macros: {
                  mb: ["\\mathbf{#1}", 1],
                  bs: ["\\boldsymbol{#1}", 1],
                  cD: "\\mathcal{D}",
                  cF: "\\mathcal{F}",
                  E: "\\mathbb{E}",
                  Var: "\\text{Var}",
                  Cov: "\\text{Cov}",
                  im: "\\text{im}"
                }
              }
            };
          </script>

execute:
  freeze: auto
